{{- if and ( and (hasKey .Values.auth "passwordfile") (not ( eq .Values.auth.passwordfile ""))) .Values.persistence.passwordfile.enabled -}}
{{- include "common.values.setup" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-password
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  password-file.secret: |
{{ .Values.auth.passwordfile | indent 4 }}
{{ end }}


{{- if and ( and (hasKey .Values.auth "mqttServerCrt") (not ( eq .Values.auth.mqttServerCrt ""))) .Values.persistence.ca.enabled -}}
{{- include "common.values.setup" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-mqtt-server-crt
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  mqtt-server.crt: |
{{ .Values.auth.mqttServerCrt | indent 4 }}
{{ end }}


{{- if and ( and (hasKey .Values.auth "caCrt") (not ( eq .Values.auth.caCrt ""))) .Values.persistence.ca.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-ca-crt
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: |
{{ .Values.auth.caCrt | indent 4 }}
{{ end }}

{{- if and ( and (hasKey .Values.auth "mqttServerKey") (not ( eq .Values.auth.mqttServerKey ""))) .Values.persistence.ca.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-mqtt-server-key
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  mqtt-server.key: |
{{ .Values.auth.mqttServerKey | indent 4 }}
{{- end }}
