{{- if and ( and (hasKey .Values.auth "caCrt") (not ( eq .Values.auth.caCrt ""))) .Values.persistence.ca.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-ca-crt
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: |
{{ .Values.auth.caCrt | indent 4 }}
{{ end }}

{{- if and ( and (hasKey .Values.auth "mqttServerKey") (not ( eq .Values.auth.mqttServerKey ""))) .Values.persistence.ca.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-mosquitto.key
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  mosquitto.key: |
{{ .Values.auth.mqttServerKey | indent 4 }}
  mosquitto.crt: |
{{ .Values.auth.mqttServerCrt | indent 4 }}
  mosquitto-passwords: |
{{ .Values.auth.passwordfile | indent 4 }}
{{- end }}
